version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloudformation-output-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ev27y09pimtu"
s3_prefix = "cloudformation-output-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
